### ISSUE TITLE
Internal error with PG

### ISSUE THREAD

**Issue by seidlmic** [piccio/redmine_watchers_groups#4] opened 2019-03-06 10:09 UTC
Server error while creating new issue or viewing issue.

`  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL`

`ActionView::Template::Error (PG::GroupingError: ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "users".* FROM "users" INNER JOIN "groups_users" ON "...
               ^
: SELECT "users".* FROM "users" INNER JOIN "groups_users" ON "groups_users"."group_id" = "users"."id" WHERE "users"."type" IN ('Group', 'GroupBuiltin', 'GroupAnonymous', 'GroupNonMember') AND (groups_users.user_id IN (6)) GROUP BY "grou$
     9:
    10: <h3><%= l(:label_issue_watchers) %> (<%= watched.watcher_users.size %>)</h3>
    11:
    12: <%= watchers_list(watched) %>  
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:41:in `block in watcher_groups'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:27:in `each'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:27:in `watcher_groups'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/watchers_helper_patch.rb:14:in `watchers_groups_list'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/watchers_helper_patch.rb:6:in `watchers_list'
`

**Comment by tguiot** [comment] 2019-04-03 07:55
I'm also having an interal error on the ticket for which I added a group as observer.
Redmine version 3.4.6

logs:

```
ActionView::Template::Error (PG::GroupingError: ERROR:  column "users.id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT "users".* FROM "users" INNER JOIN "groups_users" ON "...
               ^
: SELECT "users".* FROM "users" INNER JOIN "groups_users" ON "groups_users"."group_id" = "users"."id" WHERE "users"."type" IN ('Group', 'GroupBuiltin', 'Gr$
     9:
    10: <h3><%= l(:label_issue_watchers) %> (<%= watched.watcher_users.size %>)</h3>
    11:
    12: <%= watchers_list(watched) %>
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:41:in `block in watcher_groups'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:27:in `each'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/group_patch.rb:27:in `watcher_groups'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/watchers_helper_patch.rb:14:in `watchers_groups_list'
  plugins/redmine_watchers_groups/lib/redmine_watchers_groups/watchers_helper_patch.rb:6:in `watchers_list'
  app/views/watchers/_watchers.html.erb:12:in `_app_views_watchers__watchers_html_erb___361314524718638353_47057508327300'
  app/views/issues/show.html.erb:160:in `block in _app_views_issues_show_html_erb__3193715291476343509_70193765771420'
  app/views/issues/show.html.erb:154:in `_app_views_issues_show_html_erb__3193715291476343509_70193765771420'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/custom_middleware.rb:62:in `call'
```

**Comment by piccio** [comment] 2019-04-08 14:30
Duplicate of #3

**Closed as completed by piccio** 2019-04-08 14:30 UTC
